"""initial migration

Revision ID: 6b8da157a9b6
Revises: 
Create Date: 2023-11-15 19:30:19.828797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b8da157a9b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_menu_item_title'), ['title'], unique=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('joined_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_joined_at'), ['joined_at'], unique=False)
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_index(batch_op.f('ix_user_joined_at'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_column('joined_at')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('email')

    with op.batch_alter_table('menu_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menu_item_title'))

    # ### end Alembic commands ###
