"""hey

Revision ID: 88460f3bdc87
Revises: 6b8da157a9b6
Create Date: 2023-11-19 11:16:14.039539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88460f3bdc87'
down_revision = '6b8da157a9b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_purchase_time'), ['time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_time'))
        batch_op.drop_column('time')

    # ### end Alembic commands ###
