"""dollars

Revision ID: cbe73dcd5912
Revises: 88460f3bdc87
Create Date: 2023-11-27 19:10:58.264491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbe73dcd5912'
down_revision = '88460f3bdc87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_price_dollars', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('unit_price_cents', sa.Integer(), nullable=True))
        batch_op.drop_column('unit_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_price', sa.INTEGER(), nullable=True))
        batch_op.drop_column('unit_price_cents')
        batch_op.drop_column('unit_price_dollars')

    # ### end Alembic commands ###
